FROM --platform=linux/amd64 ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main
RUN apt-get update && apt-get install -y --no-install-recommends libopus-dev libssl-dev pkg-config && rm -rf /var/lib/apt/lists/*
